dbt_core:
  outputs:
    dev:
      dataset: pkg_mart
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: aritzia-440802
      threads: 1
      type: bigquery
  target: dev
default:
  outputs:
    dev:
      dataset: pkg_mart
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: aritzia-440802
      threads: 1
      type: bigquery
  target: dev
