# Note that only one of these targets is required

my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "aritzia-440802"
      dataset: "pkg" # You can also use "schema" here
      threads: 4 # Must be a value of 1 or greater 
      [OPTIONAL_CONFIG](#optional-configurations): VALUE